### ISSUE TITLE
Feature Request: "Will be removed in" version number

### ISSUE THREAD

**Issue by SpacemanPaul** [mjhajharia/deprecat#10]
In addition to `version=` giving the "deprecated in" version number, it would be nice to be able to specify a "will be removed in" version number.

You could add another argument, e.g. say with `remove_version` or `deadline_version`.  

I can do a PR if nobody who knows the code better has the time.

**Comment by mjhajharia** [comment]
is the purpose marking items for deprecation and giving warnings that something will be deprecated soon, or is it to have separate version numbers for "deprecation" and "removal".

**Comment by SpacemanPaul** [comment]
I'm thinking of e.g. "deprecated from v1.9, will be removed in v2.0"  use case.
