### ISSUE TITLE
Release 2.1.2 hasn't been pushed to PyPI

### ISSUE THREAD

**Issue by SpacemanPaul** [mjhajharia/deprecat#14]
2.1.2 has been tagged here on github: https://github.com/mjhajharia/deprecat/releases/tag/v2.1.2

But hasn't been pushed to PyPI:

```
> pip install --upgrade --dry-run deprecat
Collecting deprecat
  ...
Would install deprecat-2.1.1 wrapt-1.16.0
```

**Comment by SpacemanPaul** [comment]
If you add me as admin here on github and on PyPI I'm happy to co-maintain.

**Comment by mjhajharia** [comment]
hey @SpacemanPaul! sorry for the delayed responses. it has been a hectic year for me personally and professionaly, I would be happy to get some help, I added you as a collaborator on github. Would you be able to shoot me an email on `meenal@mjhajharia.com` so we can see how to add you on PyPI and any other access things you might need. Thanks and apologies again!
