### ISSUE TITLE
Autogenerate the docstring examples

### ISSUE THREAD

**Issue by OriolAbril** [mjhajharia/deprecat#8]
There is a https://deprecat.readthedocs.io/en/latest/source/usage.html#docstring section which is hardcoded in rST instead of showing the actual output. 

I would try to create a showcase module inside the library that is not used by it nor exposed when imported but has one example of each deprecation type, class, function, method, kwarg... and then create a showcase api docs. I think this will serve also as a rudimentary test that the output looks as desired when doing changes in a way that automated tests can't

**Comment by mjhajharia** [comment]
this was a great idea, i did this just now https://deprecat.readthedocs.io/en/latest/source/api.html#examples thanks @OriolAbril !!!
